changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: 🚫 Bugs
      labels:
        - bug
    - title: 🚀 Features
      labels:
        - enhancement
        - feature
    - title: 🔧 Tasks
      labels:
        - task
    - title: 🔎 Tests
      labels:
        - test
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
