name: 🚀 Insiders CI

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [insider]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/template-main.yaml
    with:
      version: latest
      code_type: insider
