name: Main CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - wiki/**
      - sample-projects/**
      - README.md
      - SECURITY.md
      - KNOWN_ISSUES.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - DCO
      - LICENSE
      - .github/workflows/**
      - '!.github/workflows/main.yml'
      - '!.github/workflows/template-main.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - wiki/**
      - sample-projects/**
      - README.md
      - SECURITY.md
      - KNOWN_ISSUES.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - DCO
      - LICENSE
      - .github/workflows/**
      - '!.github/workflows/main.yml'
      - '!.github/workflows/template-main.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version: [ min, 1.86.2, max ]
    uses: ./.github/workflows/template-main.yaml
    with:
      version: ${{ matrix.version }}

  check:
    if: always()
    runs-on: ubuntu-latest
    name: Status Check
    needs: [ test ]
    steps:
      - name: Test Matrix Result
        run: |
          echo result = ${{ needs.test.result }}
      - name: Status Check - success
        if: ${{ needs.test.result == 'success' }}
        run: |
          echo "All tests successfully completed!"
          exit 0
      - name: Status Check - failure
        if: ${{ needs.test.result != 'success' }}
        run: |
          echo "Status Check failed!"
          exit 1
