name: 📄 Main CI - template

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      nodejs:
        required: false
        default: '18.x'
        type: string
      code_type:
        required: false
        default: 'stable'
        type: string

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    env:
      CODE_TYPE: ${{ inputs.code_type }}
      CODE_VERSION: ${{ inputs.version }}
      TEST_RESOURCES: test-resources

    steps:
      - name: 🔧 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔧 Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodejs }}
          cache: npm

      - name: 🔧 Install
        run: npm ci

      - name: 🔍 Run Tests (macOS, windows)
        if: matrix.os != 'ubuntu-latest'
        run: |
          npm test

      - name: 🔍 Run Tests (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npm test

      - name: 💾 Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure() && inputs.nodejs != 'lts/*'
        with:
          name: screenshots-${{ matrix.os }}-${{ inputs.version }}-node_${{ inputs.nodejs }}
          path: ${{ github.workspace }}/test/**/screenshots/*.png

      - name: 💾 Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure() && inputs.nodejs == 'lts/*'
        with:
          name: screenshots-${{ matrix.os }}-${{ inputs.version }}-node_lts
          path: ${{ github.workspace }}/test/**/screenshots/*.png
